# Inheritance (example)
#inherits:
#- role: superRole1

# Variants supported by this role
variants:
- variant: services
- variant: importer

# Relative path to lookup the template files
templateDir: tomcat

files:

# Define a single file to be generated for role variant 'services'
- file: ROOT.xml
  variants:
  - services
  dir: conf/Catalina/localhost
  template: ROOT.xml.hbs
  # Allows to define special validators.
  # If missing the best-match validator is picked automatically.
  validators:
  - xml

# Define a single file to be generated for role variant 'importer'
- file: ROOT.xml
  variants:
  - importer
  dir: conf/Catalina/localhost
  template: ROOT_importer.xml.hbs
  validators:
  - xml

# Define a single file to be generated for all role variants
- file: setenv.sh
  dir: bin
  template: setenv.sh.hbs
  # Default charset is UTF-8 unless specified otherwise
  charset: ISO-8859-1

# Generate a single file that is later renamed to another filename (which may happen in an inheriting role)
- file: setenv-to-be-renamed.bat
  dir: bin
  template: setenv.bat.hbs
  charset: ISO-8859-1
  lineEndings: windows

# Generate a file by copying from another generated file - and delete the source afterwards
- file: setenv.bat
  dir: bin
  url: file-node:bin/setenv-to-be-renamed.bat
  deleteSource: true

# Copy file from classpath
- file: mysample.txt
  dir: download
  url: classpath:/sample.txt
  modelOptions:
    customOption1: value1
    customOption2: 123

# Download file from maven repository, use artifact filename.
# Derive version from maven project.
- url: mvn:io.wcm.devops/io.wcm.devops.parent_toplevel//xml/site
  dir: download


# Defines configuration parameters and default values
config:

  tomcat:
    path: /path/to/tomcat

  jvm:
    path: /path/to/java
    heapspace:
      min: 512m
      max: 2048m
    permgenspace:
      max: 256m

  topologyConnectors:
    - http://localhost:8080/libs/sling/topology/connector
