# Relative path to lookup the template files
templateDir: webserver

files:

# Define a file to be generated per tenant
- file: "${tenant}_vhost.conf"
  dir: available_vhosts
  template: tenant_vhost.conf.hbs
  # Multiply file for each tenant that has the given roles
  multiply: tenant
  multiplyOptions:
    roles:
    - website

# Symlink pointing to a generated file
- file: "${tenant}_vhost.conf"
  dir: enabled_vhosts
  symlinkTarget: "available_vhosts/${tenant}_vhost.conf"
  # Multiply file for each tenant that has the given roles
  multiply: tenant
  multiplyOptions:
    roles:
    - website


# Defines configuration parameters and default values
config:
  website.hostname: host
