# Defines an environment
nodes:

# Example node with 2 roles
- node: services-1
  # Config for all roles in this node
  config:
    jvm.heapspace.max: 2048m
    topologyConnectorPath: /specialConnector
  roles:
  - role: tomcat-services
    # Variants allow to pick a specific sub-configuration of a role
    variant: importer
    # Config only for this role
    config:
      topologyConnectors:
      # Merge with list defined already for this parameter
      - _merge_
      - "http://host3${topologyConnectorPath}"
  - role: tomcat-backendconnector

# Example node with 1 role
- node: services-2
  roles:
  - role: tomcat-services
    variant: services

# Example node with 1 role
- node: webserver
  roles:
  - role: webserver




# Role-specific global configuration
roleConfig:
- role: role1
  config:
    var1: v1


# Global configuration
config:
  # It is possible to use a shortcut definition for nested maps.
  #   jvm.heapspace.max: 4096m
  # is equivalent to
  #   jvm:
  #     heapspace:
  #       max: 4096m
  jvm.heapspace.max: 4096m
  # Configuration entries can be used as variables for other entries
  topologyConnectorPath: /connector
  topologyConnectors:
  - "http://host1${topologyConnectorPath}"
  - "http://host2${topologyConnectorPath}"


# Tenant definitions
tenants:

# Tenant with two tenant roles (can be used for filtering file multiply)
- tenant: tenant1
  roles:
  - website
  - application
  config:
    domain: mysite.de
    website.hostname: ${'www.' + domain}

# Tenant with one tenant role
- tenant: tenant2
  roles:
  - website
  config:
    domain: mysite.fr
    website.hostname: ${'www.' + domain}
