/*
 * #%L
 * wcm.io
 * %%
 * Copyright (C) 2015 wcm.io
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */
package io.wcm.devops.conga.generator.spi;

import java.util.Map;

/**
 * Context for each file generated by a {@link MultiplyPlugin}.
 */
public final class MultiplyContext {

  private final String file;
  private final String dir;
  private final Map<String, Object> config;

  /**
   * @param file File
   * @param dir Directory
   * @param config Configuration
   */
  public MultiplyContext(String file, String dir, Map<String, Object> config) {
    this.file = file;
    this.dir = dir;
    this.config = config;
  }

  public String getFile() {
    return this.file;
  }

  public String getDir() {
    return this.dir;
  }

  public Map<String, Object> getConfig() {
    return this.config;
  }

}
