name: Release from Tag

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        body: 'Changes: https://devops.wcm.io/conga/changes-report.html'
        token: ${{ secrets.GITHUB_TOKEN }}
